apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: o6ggiirxa-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: o6ggiirxa-python 
  name: o6ggiirxa-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: o6ggiirxa-python 
