apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: o6ggiirxa-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-de413252c4.8vpp.p3.openshiftapps.com/rhtap/rhtap-qe:803ce72199c312a6da713f956d53f2e3fbe4fc26@sha256:c2e23ebadac6b0104478b5636ea934031f282d8c88b1871a7f7ef3730e973f90
          name: container-image
